### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by postits** [NoM0Re/AddFriend-3.3.5a#1]
Not adding options to menu:
Tried disabling all other addons in case of conflict - Still not working.

**Comment by NoM0Re** [comment]
Hi,
This version of the addon is strictly for Patch 3.3.5a Retail WotLK currently only playable on private servers.
Also make sure that you followed the installation instructions: https://github.com/NoM0Re/AddFriend-3.3.5a#installation
I use it myself and its working well.

**Comment by postits** [comment]
Must be my mistake then.
Currently playing on Warmane which lists "Version 3.3.5 (12340) (Release)" on the login screen, although it says 3.3.5a when downloading the client.

Tried it on two different clients following the installation instructions, and no go.

________________________________

**Comment by NoM0Re** [comment]
Sorry, I had to ask if you were playing on the correct game version.
I updated it this should fix the issue. I linked the library files incorrectly, which is why the addon wasn't loading for you.
I didn't have the issue because I had other addons loading the library already.
Thanks for opening the issue.

**Comment by postits** [comment]
I get that, I should've listed it in the first post.
It does indeed work now, awesome - Thanks for updating.

This issue can be closed.
